name: run-tests
on: [push, pull_request]

jobs:
  build-deploy:
    runs-on: ubuntu-latest         # use GitHub-hosted runner (or keep matrix/os if you need matrix)
    steps:
      - uses: actions/checkout@v4

      - name: Install valgrind (if needed)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y valgrind

      - name: make test
        run: make test CFLAGS=-fPIC

      - name: make valgrind_test
        if: runner.os == 'Linux'
        run: make valgrind_test CFLAGS=-fPIC

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: compiled-${{ runner.os }}
          path: .
